feat(tutoriales): new llaves de github section
eoscostarica/guias.eoscostarica.io pull request #222
Opened 2021-01-28 00:17 UTC by Edgar097

### GH Issue

Resolves #214  

### Steps to test
1. Go to Llaves de GitHub
1. Check Content

#### CheckList
- [ ] Follow proper Markdown format
- [ ] The content is adequate
- [ ] The content is available in both english and spanish
- [ ] I Ran a spell check

2021-01-28 03:50 UTC, xavier506 commented on docs/tutoriales/llaves-github.md
> +## ¿Cómo generar una nueva clave SSH?
## ¿Cómo generar una nueva clave SSH en windows?

2021-01-28 04:07 UTC, xavier506 approved these changes
LGTM

2021-01-28 14:46 UTC, leisterfrancisco requested changes

2021-01-28 14:46 UTC, leisterfrancisco commented on docs/tutoriales/llaves-github.md
> +- Asegúrate de que el ssh-agent se está ejecutando [más información](https://docs.github.com/en/free-pro-team@latest/github/authenticating-to-github/working-with-ssh-key-passphrases) , o inícialo man
👾 Empty space 👾
> /working-with-ssh-key-passphrases) ,

2021-01-28 15:36 UTC, steph222 commented on docs/tutoriales/llaves-github.md
> +- Ahora necesitas añadir tu clave pública a tu cuenta de **GitHub** , para ello [sigue estos pasos](https://docs.github.com/en/free-pro-team@latest/github/authenticating-to-github/adding-a-new-ssh-ke
Empty space!

>**GitHub**,

2021-01-29 01:39 UTC, xavier506 approved these changes
LGTM

2021-01-29 15:13 UTC, leisterfrancisco approved these changes
Good work

2021-01-29 15:15 UTC, merged