feat(docker): new section
eoscostarica/guias.eoscostarica.io pull request #241
Opened 2021-02-05 03:01 UTC by Edgar097

### GH Issue

Resolves #230  

### Steps to test
1. Tutorials
1. Docker
1. Check Content

#### CheckList
- [ ] Follow proper Markdown format
- [ ] The content is adequate
- [ ] The content is available in both english and spanish
- [ ] I Ran a spell check

2021-02-05 16:21 UTC, xavier506 commented on docs/tutoriales/docker.md
> +Docker Engine es una tecnología de contenedorización de código abierto para crear y contener sus aplicaciones. Docker Engine actúa como una aplicación cliente-servidor con:
contendorizacion?

2021-02-05 16:23 UTC, xavier506 commented on docs/tutoriales/docker.md
> +
Docker es una herramienta que permite crear, probar e implementar aplicaciones rápidamente. La idea detrás de Docker es crear “contenedores” que sean ligeros y portátiles para que las aplicaciones se puedan ejecutar en cualquier máquina con Docker instalado, independientemente del sistema operativo.

Por ejemplo cada nodo de la red blockchain o servicio / aplicación desarrollado será compilado en una imagen docker que contiene la totalidad de sus dependencias y es desplegada a una a varios proveedores de infraestructura con docker disponible.

2021-02-05 16:24 UTC, xavier506 commented on docs/tutoriales/docker.md
> +
Posiblemente esta tabla ayude a visualizar los conceptos

![image](https://user-images.githubusercontent.com/5632966/107060181-47acd400-679c-11eb-8cd9-e3eb6a2cdda4.png)

2021-02-05 16:26 UTC, xavier506 commented
Por favor coordinar los cambios en el contenido que se esta trabajando en ingles. #230

2021-02-05 16:42 UTC, xavier506 commented on docs/tutoriales/docker.md
> +
Adicional a Docker utilizamos una herramienta “orquestadora” de contenedores llamada Kubernetes (K8s).

Kubernetes ayuda a administrar los contenedores en los cuales están alojadas las aplicaciones de una forma fácil, rápida y escalable. Además, también cuenta con monitoreo y balanceo de carga. Sobre los servidores virtuales. 

Valdra la pena  hacer un link a la parte de k8s en la pagina de devOps?

2021-02-05 16:49 UTC, xavier506 commented on docs/tutoriales/docker.md
> +
Y un link de devops a esta pagina?

2021-02-05 17:07 UTC, leisterfrancisco requested changes

2021-02-05 17:07 UTC, leisterfrancisco commented on docs/tutoriales/docker.md
> +## Cómo empezar
Title case

2021-02-05 17:07 UTC, leisterfrancisco commented on docs/tutoriales/docker.md
> +### Estructura de Proyecto
Title case

2021-02-05 17:07 UTC, leisterfrancisco commented on docs/tutoriales/docker.md
> +### Desglose del Código
Title case

2021-02-05 17:07 UTC, leisterfrancisco commented on docs/tutoriales/docker.md
> +#### Build the Image
Title case

2021-02-05 17:11 UTC, Edgar097 commented
We gonna use Title Case for the monosyllables?

2021-02-05 17:16 UTC, leisterfrancisco commented
> 
> 
> We gonna use Title Case for the monosyllables?

No, only if is the first letter

2021-02-05 18:05 UTC, xavier506 commented on docs/tutoriales/docker.md
> +![aplicación_docker](https://user-images.githubusercontent.com/5632966/107060181-47acd400-679c-11eb-8cd9-e3eb6a2cdda4.png)
Maybe we can find a better image than this

2021-02-05 22:55 UTC, xavier506 commented on docs/tutoriales/docker.md
> +![Estructura Docker](https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Docker-containerized-and-vm-transparent-bg.png/800px-Docker-containerized-and-vm-transparent-bg.png)
instead of pulling the image from an external source lets download it and include it in our own repo

2021-02-05 23:54 UTC, xavier506 commented on docs/tutoriales/docker.md
> +<img alt="documentation-images"   src={ useBaseUrl( '/img/documentation-images/Docker-containerized-and-vm-transparent-bg.png' )} />
`alt="Docker vs. Traditional VMs"`

2021-02-06 03:19 UTC, xavier506 approved these changes
LGTM

2021-02-06 03:19 UTC, merged