docs: private-network-tutorial
eoscostarica/guias.eoscostarica.io pull request #250
Opened 2021-02-08 22:14 UTC by JustinCast

### GH Issue

#268

### Steps to test
1. `yarn start`
1. Go to localhost:3000 and search instalacion-de-red-privada

#### CheckList
- [x] Follow proper Markdown format
- [x] The content is adequate
- [x] The content is available in both english and spanish
- [x] I Ran a spell check

2021-02-09 14:49 UTC, leisterfrancisco requested changes

2021-02-09 14:49 UTC, leisterfrancisco commented on docs/tutoriales/instalacion-de-red-privada.md
> +# Instalación y configuración de una red privada
Title Case

2021-02-09 14:49 UTC, leisterfrancisco commented on docs/tutoriales/instalacion-de-red-privada.md
> +# Requisitos previos de software
Title Case

2021-02-09 14:49 UTC, leisterfrancisco commented on docs/tutoriales/instalacion-de-red-privada.md
> +## Instalación de los binarios precompilados de EOSIO
Title Case

2021-02-09 14:49 UTC, leisterfrancisco commented on docs/tutoriales/instalacion-de-red-privada.md
> +## Instalación de los binarios EOSIO.CDT (Contract Development Toolkit)
Title Case

2021-02-09 14:49 UTC, leisterfrancisco commented on docs/tutoriales/instalacion-de-red-privada.md
> +# Configuración del nodo génesis
Title Case

2021-02-09 14:49 UTC, leisterfrancisco commented on docs/tutoriales/instalacion-de-red-privada.md
> +# Iniciar el servicio nodeos
Title Case

2021-02-09 14:49 UTC, leisterfrancisco commented on docs/tutoriales/instalacion-de-red-privada.md
> +# Registros del servicio nodeos
Title Case

2021-02-09 14:49 UTC, leisterfrancisco commented on docs/tutoriales/instalacion-de-red-privada.md
> +# Configuración y compilación de `eosio.contracts`
Title Case

2021-02-09 14:49 UTC, leisterfrancisco commented on docs/tutoriales/instalacion-de-red-privada.md
> +# Despliegue del contrato `eosio.bios`
Title Case

2021-02-09 14:49 UTC, leisterfrancisco commented on docs/tutoriales/instalacion-de-red-privada.md
> +## Despliegue de la versión **antigua** de los contratos
Title Case

2021-02-09 14:49 UTC, leisterfrancisco commented on docs/tutoriales/instalacion-de-red-privada.md
> +## Desplegar la última versión de los contratos
Title Case

2021-02-09 14:49 UTC, leisterfrancisco commented on docs/tutoriales/instalacion-de-red-privada.md
> +# Nodos productores de bloques: configuración y ejecución
Title Case

2021-02-09 14:49 UTC, leisterfrancisco commented on docs/tutoriales/instalacion-de-red-privada.md
> +# Nodo API: configuración y ejecución
Title Case

2021-02-09 14:49 UTC, leisterfrancisco commented on docs/tutoriales/instalacion-de-red-privada.md
> +# Nodo semilla: configuración y ejecución
Title Case

2021-02-09 14:49 UTC, leisterfrancisco commented on docs/tutoriales/instalacion-de-red-privada.md
> +# Detener el servicio nodeos
Title Case

2021-02-09 14:49 UTC, leisterfrancisco commented on docs/tutoriales/instalacion-de-red-privada.md
> +# Reiniciar el servicio nodeos
Title Case

2021-02-09 14:49 UTC, leisterfrancisco commented on docs/tutoriales/instalacion-de-red-privada.md
> +# Reiniciar nodeos desde cero
Title Case

2021-02-09 14:49 UTC, leisterfrancisco commented on docs/tutoriales/instalacion-de-red-privada.md
> +# Interactuar con la red
Title Case

2021-02-09 14:49 UTC, leisterfrancisco commented on docs/tutoriales/instalacion-de-red-privada.md
> +## Obtener datos almacenados
Title Case

2021-02-10 16:31 UTC, leisterfrancisco submitted a review, later dismissed
Good work 👍

2021-02-10 17:21 UTC, Edgar097 commented
@JustinCast Shouldn't it be added to the sidebar? I think we are using H2 titles and we leave H1 to the section title.

2021-02-11 14:45 UTC, xavier506 approved these changes
LGTM

2021-02-12 16:57 UTC, xavier506 requested changes
@JustinCast 

Please have a look at the header tags, we should use up to h2 tags (not h1)

2021-02-12 17:20 UTC, JustinCast commented
Gonna check now

2021-02-12 17:29 UTC, JustinCast commented
> @JustinCast Shouldn't it be added to the sidebar? I think we are using H2 titles and we leave H1 to the section title.

Lemme know if there's anything wrong. It's now fixed.

2021-02-12 18:04 UTC, xavier506 approved these changes
LGTM

2021-02-12 18:30 UTC, merged