feat(ricardian-contracts): content and compiling example
eoscostarica/guias.eoscostarica.io pull request #274
Opened 2021-07-02 17:18 UTC by leisterfrancisco

### What does this PR do ?
Add clauses and contracts explanation of a Ricardian Contract

### Steps to test
1. yarn install
1. yarn start
1. go to http://localhost:3000/docs/aprender-eosio/contratos-ricardianos

#### CheckList
- [ ] Follow proper Markdown format
- [ ] The content is adequate
- [ ] The content is available in both english and spanish
- [ ] I Ran a spell check

2021-07-02 19:37 UTC, AngeloCG97 approved these changes

2021-07-04 20:50 UTC, xavier506 approved these changes
LGTM

2021-07-04 20:54 UTC, xavier506 requested changes
@leisterfrancisco  lets include a link to our react component that renders ricardian contracts:

https://components.eosio.cr/

2021-07-07 20:37 UTC, xavier506 approved these changes
LGTM

2021-07-07 20:37 UTC, merged