Update issue templates
eoscostarica/guias.eoscostarica.io pull request #293
Opened 2022-01-19 15:33 UTC by xavier506

2022-01-20 13:50 UTC, xavier506 commented
lets delete the english files 

`bug_report.md` 
`feature_request.md`

2022-01-24 07:41 UTC, leisterfrancisco requested changes
@hanakoori01 the PR name is `Update issue templates` but the file changes seem to include something else than just an update to the issue template, take a look.

2022-01-24 07:42 UTC, leisterfrancisco commented
@hanakoori01 take a look at the merge conflicts. Let me know if you need some help.

2022-01-25 17:18 UTC, leisterfrancisco approved these changes

2022-01-25 17:18 UTC, merged