refactor(frontend): New descriptive hyperlink ESP #523
eoscostarica/guias.eoscostarica.io pull request #382
Opened 2022-07-19 21:39 UTC by JAMares

### refactor(frontend): New descriptive hyperlink ESP #523

### What does this PR do?

- resolves #523

### Steps to test
1. Go to VSCode and search "enlace]", "información]", aquí]", guía]"

#### CheckList
- [X] Follow proper Markdown format
- [X] The content is adequate
- [X] The content is available in both english and spanish
- [X] I Ran a spell check

2022-07-19 22:10 UTC, warnerHurtado reviewed
LGTM

2022-07-20 02:22 UTC, xavier506 commented on docs/aprender-eosio/funciones-importantes.md
> +Los contratos inteligentes de EOSIO son simples archivos de WebAssembly. El formato WebAssembly permite definir importaciones, funciones que no se declaran en WASM en sí pero en el entorno en el que
encontrar  en el siguiente enlace: [Funciones Intrínsecas EOSIO]

2022-07-20 15:19 UTC, JAMares commented on docs/aprender-eosio/funciones-importantes.md
> +Los contratos inteligentes de EOSIO son simples archivos de WebAssembly. El formato WebAssembly permite definir importaciones, funciones que no se declaran en WASM en sí pero en el entorno en el que
Fixed up

2022-07-20 16:53 UTC, xavier506 requested changes
view comments

2022-07-20 20:04 UTC, xavier506 approved these changes
LGTM

2022-07-20 20:04 UTC, merged