docs(frontend): add blog link to security page
eoscostarica/guias.eoscostarica.io pull request #385
Opened 2022-07-21 19:42 UTC by warnerHurtado

### Add blog link to security page

### What does this PR do?

- resolves #524

### Steps to test
1. Go to Learn EOSIO in guias
2. Click on Seguridad Blockchain
3. Se the new feature

#### CheckList
- [ ] Follow proper Markdown format
- [ ] The content is adequate
- [ ] The content is available in both english and spanish
- [ ] I Ran a spell check

2022-07-21 20:22 UTC, JAMares reviewed
LGTM

2022-07-21 23:47 UTC, xavier506 commented on docs/aprender-eosio/seguridad-blockchain.md
> + Por lo que hemos vivido en carne propia algunos ataques en los que los atacantes han sido capaces de robar información de algunos sistemas, como es el caso del ataque a **(EOS SX Vault)**. En este c
Hemos presenciando algunos ataques en los que los atacantes han sido capaces de robar información o inclusive fondos de usuarios, como es el caso de... 

Para este ataque nuestro equipo realizó un seguimiento completo para analizar y aprender de la vulnerabilidad...

2022-07-21 23:48 UTC, xavier506 requested changes
Prefiero evitar decir que vivimos un ataque en "carne propio" ya que no fue en un proyecto nuestro

2022-07-22 16:45 UTC, warnerHurtado commented on docs/aprender-eosio/seguridad-blockchain.md
> + Por lo que hemos vivido en carne propia algunos ataques en los que los atacantes han sido capaces de robar información de algunos sistemas, como es el caso del ataque a **(EOS SX Vault)**. En este c
Ready

2022-07-22 17:58 UTC, xavier506 approved these changes
LGTM

2022-07-22 17:58 UTC, merged