feat(frontend): Improved footer design ESP #471
eoscostarica/guias.eoscostarica.io pull request #393
Opened 2022-07-27 06:24 UTC by fvives99

### Improve footer styles

### What does this PR do?

- resolves https://github.com/eoscostarica/guide.eoscostarica.io/issues/471

Note: react-icons was installed: npm install react-icons --save or yarn install react-icons

### Steps to test
1. Navigate to the bottom of [guias.eosio](https://guias.eoscostarica.io/) and see page footer

#### CheckList
- [ ] Follow proper Markdown format
- [ ] The content is adequate
- [ ] The content is available in both english and spanish
- [ ] I Ran a spell check

2022-07-27 06:26 UTC, fvives99 commented
![image](https://user-images.githubusercontent.com/55892352/181176476-3e476a89-a823-41c4-b789-4278d253a196.png)

2022-07-27 17:17 UTC, JAMares requested changes
See the LGTM comments about unused and use yarn build and npm run serve to see the final result

2022-07-27 21:08 UTC, fvives99 reviewed
fixed

2022-07-29 14:27 UTC, AngeloCG97 commented on src/theme/Footer/index.js
> +     console.log(isDarkTheme)
Please remove this comment

2022-07-29 17:31 UTC, fvives99 commented on src/theme/Footer/index.js
> +     console.log(isDarkTheme)
removed.

2022-07-29 20:47 UTC, xavier506 approved these changes
LGTM

2022-08-02 14:08 UTC, AngeloCG97 approved these changes
LGTM

2022-08-02 14:25 UTC, merged

2022-08-03 23:42 UTC, fvives99 commented
![image](https://user-images.githubusercontent.com/55892352/182731214-4cecf5b0-7ae8-41a2-a472-50c946607d04.png)
@AngeloCG97 mobile footer